package fr.tsodev.integration.impl;


public class AssetManagementConstants {
    
    public static final String ASSETMANAGEMENT_PROGRAM_BUNDLE_ID = "fr.tsodev.assetmgmt";
    
    public static final String ASSETMANAGEMENT_ASSET_RECORD_NAME = "fr.tsodev.assetmgmt:Asset";
    public static final String ASSETMANAGEMENT_CONTRACT_RECORD_NAME = "fr.tsodev.assetmgmt:Contract";
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_RECORD_NAME = "fr.tsodev.assetmgmt:Product Catalog";
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_RECORD_NAME = "fr.tsodev.assetmgmt:Inventory Location";
    

	public final static String SETTINGS_ASSETMANAGEMENT_COMPONENT_REMEDYSERVER = "Remedy Server";
	public final static String SETTINGS_ASSETMANAGEMENT_SETTING_URL = "url";
    public final static String SETTINGS_ASSETMANAGEMENT_SETTING_USERNAME = "username";
    public final static String SETTINGS_ASSETMANAGEMENT_SETTING_PASSWORD = "password";
    

    public final static String SETTINGS_ASSETMANAGEMENT_COMPONENT_LOGGER = "Logger Configuration";
    public final static String SETTINGS_ASSETMANAGEMENT_SETTING_FILENAME = "fileName";
    public final static String SETTINGS_ASSETMANAGEMENT_SETTING_LEVEL = "level";
    
	
	public static final String ASSETMANAGEMENT_PRODUCT_IN_CONTRACT_ASSOCIATION = ASSETMANAGEMENT_PROGRAM_BUNDLE_ID + ":" + "Product in Contract";
	public static final String ASSETMANAGEMENT_INVENTORYLOCATION_IN_CONTRACT_ASSOCIATION = ASSETMANAGEMENT_PROGRAM_BUNDLE_ID + ":" + "Stock for Contract";
	public static final String ASSETMANAGEMENT_ASSETS_IN_CONTRACT_ASSOCIATION = ASSETMANAGEMENT_PROGRAM_BUNDLE_ID + ":Assets in Contract";
	
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_1_FIELD_ID_STRING = "536870914";
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_2_FIELD_ID_STRING = "536870915";
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_3_FIELD_ID_STRING = "536870916";
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_MANUFACTURER_FIELD_ID_STRING = "536870919";
    public static final String ASSETMANAGEMENT_PRODUCT_CATALOG_MODEL_FIELD_ID_STRING = "536870918";

    
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_REGION_FIELD_ID_STRING = "536870916";
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_SITE_FIELD_ID_STRING = "536870917";
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_BUILDING_FIELD_ID_STRING = "536870918";
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_ROOM_FIELD_ID_STRING = "536870920";
    public static final String ASSETMANAGEMENT_INVENTORY_LOCATION_FLOOR_FIELD_ID_STRING = "536870919";
    
    public static final String ASSETMANAGEMENT_ASSET_DESCRIPTION_FIELD_ID_STRING = "8";
    public static final String ASSETMANAGEMENT_ASSET_NAME_FIELD_ID_STRING = "536870914";
    public static final String ASSETMANAGEMENT_ASSET_CATEGORY_FIELD_ID_STRING = "536870915";
    public static final String ASSETMANAGEMENT_ASSET_TYPE_FIELD_ID_STRING = "536870916";
    public static final String ASSETMANAGEMENT_ASSET_ITEM_FIELD_ID_STRING = "536870917";
    public static final String ASSETMANAGEMENT_ASSET_REGION_FIELD_ID_STRING = "536870918"; 
    public static final String ASSETMANAGEMENT_ASSET_SITE_FIELD_ID_STRING = "536870919";
    public static final String ASSETMANAGEMENT_ASSET_BUILDING_FIELD_ID_STRING = "536870920"; 
    public static final String ASSETMANAGEMENT_ASSET_ROOM_FIELD_ID_STRING = "536870921";
    public static final String ASSETMANAGEMENT_ASSET_FLOOR_FIELD_ID_STRING = "536870922";   
    public static final String ASSETMANAGEMENT_ASSET_MODEL_FIELD_ID_STRING = "536870923";
    public static final String ASSETMANAGEMENT_ASSET_MANUFACTURER_FIELD_ID_STRING = "536870924";
    public static final String ASSETMANAGEMENT_ASSET_TAG_NUMBER_FIELD_ID_STRING = "536870925";    
    public static final String ASSETMANAGEMENT_ASSET_EXTERNAL_INSTANCE_ID_FIELD_ID_STRING = "536870913";
    public static final String ASSETMANAGEMENT_ASSET_EXTERNAL_RECONCILIATION_ID_FIELD_ID_STRING = "536870926";    

    public static final Integer ASSETMANAGEMENT_ASSET_DESCRIPTION_FIELD_ID = 8;
    public static final Integer ASSETMANAGEMENT_ASSET_NAME_FIELD_ID = 536870914;
    public static final Integer ASSETMANAGEMENT_ASSET_CATEGORY_FIELD_ID = 536870915;
    public static final Integer ASSETMANAGEMENT_ASSET_TYPE_FIELD_ID = 536870916;
    public static final Integer ASSETMANAGEMENT_ASSET_ITEM_FIELD_ID = 536870917;
    public static final Integer ASSETMANAGEMENT_ASSET_REGION_FIELD_ID = 536870918; 
    public static final Integer ASSETMANAGEMENT_ASSET_SITE_FIELD_ID = 536870919;
    public static final Integer ASSETMANAGEMENT_ASSET_BUILDING_FIELD_ID = 536870920; 
    public static final Integer ASSETMANAGEMENT_ASSET_ROOM_FIELD_ID = 536870921;
    public static final Integer ASSETMANAGEMENT_ASSET_FLOOR_FIELD_ID = 536870922;   
    public static final Integer ASSETMANAGEMENT_ASSET_MODEL_FIELD_ID = 536870923;
    public static final Integer ASSETMANAGEMENT_ASSET_MANUFACTURER_FIELD_ID = 536870924;
    public static final Integer ASSETMANAGEMENT_ASSET_TAG_NUMBER_FIELD_ID = 536870925;    
    public static final Integer ASSETMANAGEMENT_ASSET_EXTERNAL_INSTANCE_ID_FIELD_ID = 536870913;
    public static final Integer ASSETMANAGEMENT_ASSET_EXTERNAL_RECONCILIATION_ID_FIELD_ID = 536870926;    

    public static final Integer ASSETMANAGEMENT_CONTRACT_CONTRACT_ID_FIELD_ID = 1;
    public static final Integer ASSETMANAGEMENT_CONTRACT_STATUS_FIELD_ID = 7;
    public static final Integer ASSETMANAGEMENT_CONTRACT_DESCRIPTION_FIELD_ID = 8;
    public static final Integer ASSETMANAGEMENT_CONTRACT_NAME_FIELD_ID = 536870915;
    public static final Integer ASSETMANAGEMENT_CONTRACT_QUANTITY_FIELD_ID = 536870914;
    public static final Integer ASSETMANAGEMENT_CONTRACT_EXTERNAL_INSTANCE_ID_FIELD_ID = 536870913;
    public static final Integer ASSETMANAGEMENT_CONTRACT_ASSET_BASE_NAME_FIELD_ID = 536870916;
    public static final Integer ASSETMANAGEMENT_CONTRACT_EXTERNAL_URL_FIELD_ID = 536870917;
    
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_DESCRIPTION_FIELD_ID = 8;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_PRODUCT_NAME_FIELD_ID = 536870918;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_CATEGORY_1_FIELD_ID = 536870914;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_CATEGORY_2_FIELD_ID = 536870915;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_CATEGORY_3_FIELD_ID = 536870916;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_MANUFACTURER_FIELD_ID = 536870919;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_ASSET_CLASS_FIELD_ID = 536870920;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_VENDOR_NAME_FIELD_ID = 536870921;
    public static final Integer ASSETMANAGEMENT_PRODUCT_CATALOG_EXTERNAL_INSTANCE_ID_FIELD_ID = 536870913;
    
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_DESCRIPTION_FIELD_ID = 8;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_NAME_FIELD_ID = 536870914;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_COMPANY_FIELD_ID = 536870915;   
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_REGION_FIELD_ID = 536870916;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_SITE_FIELD_ID = 536870917;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_BUILDING_FIELD_ID = 536870918;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_ROOM_FIELD_ID = 536870920;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_FLOOR_FIELD_ID = 536870919;
    public static final Integer ASSETMANAGEMENT_INVENTORY_LOCATION_EXTERNAL_INSTANCE_ID_FIELD_ID = 536870913;
    
}
